services:
  cbs:
    container_name: cbs
    image: "couchbase/server:enterprise-7.1.3"
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 8096:8096
      - 11207:11207
      - 11210:11210
      - 11211:11211
      - 18091:18091
      - 18092:18092
      - 18093:18093
      - 18094:18094
  cbs-replica1:
    container_name: cbs-replica1
    image: "couchbase/server:enterprise-7.1.3"
  cbs-replica2:
    container_name: cbs-replica2
    image: "couchbase/server:enterprise-7.1.3"
